#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )
source ${BASE_DIR}/../lib/backup

# Backup before removing
backup_file "${HOME}/.vimrc"

echo "Uninstalling .vimrc"
rm -f ${HOME}/.vimrc

echo "Removing ~/.vim"
rm -rf ${HOME}/.vim
