#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )
source ${BASE_DIR}/../lib/backup

# Backup before removing
backup_file "${HOME}/.zsh_plugins.txt"
backup_file "${HOME}/.zshrc"

echo "Uninstalling .zsh_plugins.txt"
rm -f ${HOME}/.zsh_plugins.txt

# Note: Not removing .zshrc as user may have local customizations
# echo "Uninstalling .zshrc"
# rm -f ${HOME}/.zshrc
