
# Source global definitions
if [[ -f /etc/zshrc ]]; then
	. /etc/zshrc
fi

# -------------------------------------------------------------------
# Homebrew
# -------------------------------------------------------------------
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -f /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

# -------------------------------------------------------------------
# Mise Version Manager
# -------------------------------------------------------------------
if command -v mise >/dev/null 2>&1; then
    eval "$(mise activate zsh)"
fi

 # Source .profile, if it exists
 if [[ -f ${HOME}/.profile ]]; then
     . ${HOME}/.profile
 fi

# -------------------------------------------------------------------
# Antidote ZSH Plugin Manager
# -------------------------------------------------------------------
# Source Antidote from Brew Install
if command -v brew >/dev/null 2>&1; then
    if [[ -f "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh" ]]; then
        . "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh"

        # use friendly names
        zstyle ':antidote:bundle' use-friendly-names 'yes'
    fi

     if command -v antidote >/dev/null 2>&1; then
        # initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
        antidote load
    fi
fi
