#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )
source ${BASE_DIR}/../lib/backup

# Backup before removing
backup_file "${HOME}/.bashrc"

echo "Uninstalling .bashrc"
rm -f ${HOME}/.bashrc
